application:
  lang: pt-br
  title: AnsalisaRN
  subtitle: Consultoria Jurídica
  icon: /static/images/analisa.png
  logo: /static/images/analisa.png
  version: 1.0.1
  groups:
    administragdor: Administrador
    especialista: Especialista
    cliente: Cliente
    consultante: Consultante
  index: dashboard
  dashboard:
    toolbar:
    actions:
    top:
    center:
      - minhasconsultas
      - consultasaguardandoespecialista
      - consultasematendimento
      - indicadorestopicos
    boxes:
      - consultas
    search:
    usermenu:
      - icons
      - users
      - logout
    adder:
    tools:
    settings:
  menu:
    house:Início: dashboard
    user:Administradores: administradores
    list:Cadastros Gerais:
      Estados: estados
      Prioridades: prioridades
    book-reader:Base de Conhecimento:
      Assuntos: assuntos
      Especialistas: especialistas
      Perguntas Frequêntes: perguntasfrequentes
    people-line:Clientes: clientes
    file-signature:Consultoria:
      Consultas: consultas
      Estatísticas: estatisticaconsultoria
    file-signature:Consultas: consultasatendidas
    door-closed:Sair: logout
  theme:
    colors:
      primary: "#335ea9"
      secondary: "#071e41"
      auxiliary: "#2670e8"
      highlight: "#0c326f"
      info: "#335ea9"
      success: "#335ea9"
      warning: "#fff5c2"
      danger: "#e52207"
    border:
      radius: 100em"
    background:
      info: "#d4e5ff"
  oauth:
    suap:
      name: SUAP
      client_id: 8v5c0USoi6JatNOCfcti8im1elMfmp7BNHOGEcIZ
      client_secret: $SUAP_SECRET_KEY
      redirect_uri: /app/login/
      authorize_url: https://suap.ifrn.edu.br/o/authorize/
      access_token_url: https://suap.ifrn.edu.br/o/token/
      user_data_url: https://suap.ifrn.edu.br/api/eu/
      user_logout_url:
      user_scope:
      user_data:
        create: true
        username: email
        email: email
