application:
  lang: pt-br
  title: Sloth
  subtitle: Take your time!
  icon: /api/static/images/logo.png
  logo: /api/static/images/logo.png
  version: 1.0.5
  theme:
    primary: 1351b4
    secondary: 071e41
    auxiliary: 2670e8
    highlight: 0c326f
    info: d4e5ff
    success: 1351b4
    warning: fff5c2
    danger: e52207
    radius: 100em
  oauth:
    govbr:
      name: gov.br
      client_id: $GOVBR_CLIENTE_ID
      client_secret: $GOVBR_CLIENT_SECRET
      redirect_uri: /app/login/govbr/
      authorize_url: $GOVBR_AUTHORIZE_URL
      access_token_url: $GOVBR_ACCESS_TOKEN_URL
      user_data_url: $GOVBR_USER_DATA_URL
      user_logout_url: $GOVBR_LOGOUT_URL
      user_scope:
      user_data:
        create: false
        username: sub
        email: email
  groups:
    administrador: Administrador
    operador: Operador
  index: dashboard
  dashboard:
    top:
      - cadastrarpessoa2
      - listarpessoas
    center:
      - estatisticas
      - adduser
    boxes:
      - listarfuncionario
      - listarpessoas
      - listarcidades
    search:
      - listarfuncionario
      - listarpessoas
      - listarcidades
    usermenu:
      - icons
      - users
      - logout
    adder:
      - listarfuncionario
      - listarpessoas
      - listarcidades
    tools:
      - listarfuncionario
      - listarpessoas
      - listarcidades
    settings:
      - listarfuncionario
      - listarpessoas
      - listarcidades
  menu:
    list:Cadastros Gerais:
      Pessoas Físicas: pessoasfisicas
      Estados: estados
      Municípios: municipios
    user-pen:Formação:
      Instrumentos Avaliativos: instrumentosavaliativos
    users:Usuários e Papéis:
      Usuários: users
    sign-out-alt:Sair: logout
