application:
  lang: pt-br
  title: Telessaúde
  subtitle: Sistema de Telessaúde de Campo Grande
  icon: /static/images/icon.png
  logo: /static/images/logo.svg
  version: 1.0.5
  sponsors:
    - /static/images/logos/logo1.png
    - /static/images/logos/logo2.png
    - /static/images/logos/logo3.png
    - /static/images/logos/logo4.png
    - /static/images/logos/logo5.svg
  oauth:
    govbr:
      name: gov.br
      client_id: $GOVBR_CLIENTE_ID
      client_secret: $GOVBR_CLIENT_SECRET
      redirect_uri: /app/login/govbr/
      authorize_url: $GOVBR_AUTHORIZE_URL
      access_token_url: $GOVBR_ACCESS_TOKEN_URL
      user_data_url: $GOVBR_USER_DATA_URL
      user_logout_url: $GOVBR_LOGOUT_URL
      user_scope:
      user_data:
        create: false
        username: sub
        email: email
  groups:
    ge: Gestor Estadual
    gm: Gestor Municipal
    gu: Gestor de Unidade
    ou: Operador de Unidade
    ps: Profissinal de Saúde
    pf: Pessoa Física
  index: dashboard
  dashboard:
    toolbar:
      - pessoafisicas
      - estabelecimentossaude
      - profissionaissaude
      - atendimentos
    actions:
    top:
    center:
      - atendimentos
      - meuslocaisatendimento
      - minhasteleconsultas
    boxes:
      - pessoafisicas
      - estabelecimentossaude
      - profissionaissaude
      - atendimentos
      - estatistica
    adder:
      - fazeralgo
    search:
    usermenu:
      #- icons
      - users
      - logout
    tools:
    settings:
  menu:
    list:Cadastros Gerais:
      Cids: cids
      Ciaps: ciaps
      Níveis de Formacão: niveisformacao
      Sexos: sexos
      Tipos de Atendimento: tiposatendimento
      Estados: unidadesfederativas
      Municípios: municipios
    building:Estabelecimentos de Saude: estabelecimentossaude
    stethoscope:Profissionais de Saúde:
      Áreas: areass
      Especialidades: especialidades
      Vínculos Profissionais: profissionaissaude
    users:Pessoas Físicas: pessoafisicas
    laptop-file:Teleconsultas: atendimentos
    file-signature:Certificados Digitais: certificadosdigitais
  theme:
    colors:
      primary: "#265890"
      secondary: "#071e41"
      auxiliary: "#2670e8"
      highlight: "#0c326f"
      info: "#265890"
      success: "#5ca05d"
      warning: "#fff5c2"
      danger: "#e52207"
    border:
      radius: 100em"
    background:
      info: "#d4e5ff"
