application:
  lang: pt-br
  title: CECATE
  subtitle: Sistema CECATE-NE
  icon: /api/static/images/logo.png
  logo: /api/static/images/logo.png
  version: 1.0.5
  oauth:
    govbr:
      name: gov.br
      client_id: $GOVBR_CLIENTE_ID
      client_secret: $GOVBR_CLIENT_SECRET
      redirect_uri: /app/login/govbr/
      authorize_url: $GOVBR_AUTHORIZE_URL
      access_token_url: $GOVBR_ACCESS_TOKEN_URL
      user_data_url: $GOVBR_USER_DATA_URL
      user_logout_url: $GOVBR_LOGOUT_URL
      user_scope:
      user_data:
        create: false
        username: sub
        email: email
  groups:
    pf: Pessoa Física'
  index: dashboard
  dashboard:
    top:
    center:
      - responderquestionariopendente
    boxes:
      - estados
      - municipios
    search:
      - municipios
      - estados
    usermenu:
      - icons
      - logout
    adder:
    tools:
    settings:
  menu:
    house:Início: dashboard
    list:Cadastros Gerais:
      Pessoas Físicas: pessoasfisicas
      Estados: estados
      Municípios: municipios
    user-pen:Formação:
      Instrumentos Avaliativos: instrumentosavaliativos
    users:Usuários e Papéis:
      Usuários: users
    sign-out-alt:Sair: logout
