application:
  lang: pt-br
  title: CECATE
  subtitle: Sistema CECATE-NE
  icon: /static/images/logo.png
  logo: https://www.gstatic.com/images/branding/googlelogo/svg/googlelogo_dark_clr_74x24px.svg
  version: 1.0.5
  oauth:
    govbr:
      name: gov.br
      client_id: $GOVBR_CLIENTE_ID
      client_secret: $GOVBR_CLIENT_SECRET
      redirect_uri: /app/login/govbr/
      authorize_url: $GOVBR_AUTHORIZE_URL
      access_token_url: $GOVBR_ACCESS_TOKEN_URL
      user_data_url: $GOVBR_USER_DATA_URL
      user_logout_url: $GOVBR_LOGOUT_URL
      user_scope:
      user_data:
        create: false
        username: sub
        email: email
  groups:
    pf: Pessoa Física'
  index: dashboard
  dashboard:
    top:
    center:
      - responderquestionariopendente
    boxes:
      - pessoasfisicas
      - estados
    search:
      - pessoasfisicas
    usermenu:
      - icons
      - logout
    adder:
    tools:
    settings:
  menu:
    house:Início: dashboard
    list:Cadastros Gerais:
      Ensino:
        Níveis de Ensino: niveisensino
        Situação de Escolaridade: situacoesescolaridade
      Organização:
        Poderes: poderes
        Esferas: esferas
        Tipos de Orgãos: tiposorgao
        Orgãos: orgaos
      Pessoas:
        Pessoas Físicas: pessoasfisicas
      Estados e Municípios:
        Estados: estados
        Municípios: municipios
      Redes Sociais:
        Tipos de Rede Social: tiposredesocial
    user-pen:Formação:
      Instrumentos Avaliativos: instrumentosavaliativos
    users:Usuários e Papéis:
      Usuários: users
    sign-out-alt:Sair: logout
