application:
  lang: pt-br
  title: AnsalisaRN
  subtitle: Consultoria Jurídica
  icon: /static/images/analisa.png
  logo: /static/images/analisa.png
  version: 1.0.0
  groups:
    administrador: Administrador
    especialista: Especialista
    cliente: Cliente
    consultante: Consultante
  index: dashboard
  dashboard:
    top:
    center:
      - minhasconsultas
      - consultasaguardandoespecialista
      - consultasematendimento
      - consultasatendidas
    boxes:
    search:
    usermenu:
      - icons
      - logout
    adder:
    tools:
    settings:
  menu:
    house:Início: dashboard
    user:Administradores: administradores
    list:Cadastros Gerais:
      Estados: estados
      Prioridades: prioridades
    book-reader:Base de Conhecimento:
      Assuntos: assuntos
      Especialistas: especialistas
      Perguntas Frequêntes: perguntasfrequentes
    people-line:Clientes: clientes
    file-signature:Consultas: consultas
    chart-area:Monitoramento: bi
    door-closed:Sair: logout
