application:
  lang: pt-br
  title: AnsalisaRN
  subtitle: Consultoria Jurídica
  icon: /static/images/analisa.png
  logo: /static/images/analisa.png
  version: 1.0.1
  groups:
    administrador: Administrador
    especialista: Especialista
    cliente: Cliente
    consultante: Consultante
  index: dashboard
  dashboard:
    actions:
    top:
    center:
      - minhasconsultas
      - consultasaguardandoespecialista
      - consultasematendimento
      - indicadorestopicos
    boxes:
      - consultas
    search:
    usermenu:
      - icons
      - users
      - logout
    adder:
    tools:
    settings:
  menu:
    house:Início: dashboard
    user:Administradores: administradores
    list:Cadastros Gerais:
      Estados: estados
      Prioridades: prioridades
    book-reader:Base de Conhecimento:
      Assuntos: assuntos
      Especialistas: especialistas
      Perguntas Frequêntes: perguntasfrequentes
    people-line:Clientes: clientes
    file-signature:Consultoria:
      Consultas: consultas
      Estatísticas: estatisticaconsultoria
    file-signature:Consultas: consultasatendidas
    door-closed:Sair: logout
  theme:
    colors:
      primary: "#335ea9"
      secondary: "#071e41"
      auxiliary: "#2670e8"
      highlight: "#0c326f"
      info: "#335ea9"
      success: "#335ea9"
      warning: "#fff5c2"
      danger: "#e52207"
    border:
      radius: 100em"
    background:
      info: "#d4e5ff"
