services:
  frontend: &frontend
    hostname: frontend
    env_file:
      - base.env
      - local.env
    ports:
      - "${FRONTEND_PORT-5173}:5173"
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${API_URL}
        - VITE_VERSION=${VERSION}
    restart: always
    working_dir: /opt/deploy
    volumes:
      - .deploy/media:/opt/deploy/media
      - .deploy/static:/opt/deploy/static
    entrypoint: ./run.sh
    healthcheck:
      test: curl http://localhost:${FRONTEND_PORT-5173}
    depends_on:
      backend:
        condition: service_started
  backend: &backend
    hostname: backend
    env_file:
      - base.env
      - local.env
    ports:
      - "${BACKEND_PORT-8000}:8000"
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION}
    restart: always
    volumes:
      - .deploy/media:/opt/deploy/media
      - .deploy/static:/opt/deploy/static
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: curl http://127.0.0.1:${BACKEND_PORT-8000}/api/login/
    working_dir: /opt/deploy
    entrypoint: ./run.sh
  tester:
    <<: *backend
    depends_on:
      selenium:
        condition: service_started
      frontend:
        condition: service_healthy
    entrypoint: ./test.sh
  selenium:
    hostname: selenium
    env_file:
      - base.env
      - local.env
    ports:
      - "4444"
    build:
      context: selenium
      dockerfile: Dockerfile
    restart: always
    entrypoint: ./run.sh
  redis:
    hostname: redis
    env_file:
      - base.env
      - local.env
    image: redis
    restart: always
    ports:
      - "6379"
    command: redis-server --loglevel warning
    volumes:
      - .deploy/redis:/data
  postgres:
    env_file:
      - base.env
      - local.env
    image: postgres
    hostname: postgres
    ports:
      - "5432"
    volumes:
      - .deploy/postgres:/var/lib/postgresql/data
    healthcheck:
      test: psql -U postgres -d $$POSTGRES_DB -c "SELECT version();"
